ProStageController_accueil:
    path: /
    controller: App\Controller\ProStageController::accueil

ProStageController_entreprises:
    path: /entreprises
    controller: App\Controller\ProStageController::entreprises

ProStageController_formations:
    path: /formations
    controller: App\Controller\ProStageController::formations

ProStageController_stages:
    path: /stages/{id}
    controller: App\Controller\ProStageController::stages

ProStageController_parEntreprise:
    path: /entreprises/{id}
    controller: App\Controller\ProStageController::parEntreprise

ProStageController_parFormation:
    path: /formations/{id}
    controller: App\Controller\ProStageController::parFormation

ProStageController_ajouterEntreprise:
    path: /ajouterEntreprise
    controller: App\Controller\ProStageController::ajouterEntreprise