ProStageController_accueil:
    path: /
    controller: App\Controller\ProStageController::accueil

ProStageController_entreprises:
    path: /entreprises
    controller: App\Controller\ProStageController::entreprises

ProStageController_formations:
    path: /formations
    controller: App\Controller\ProStageController::formations

ProStageController_stages:
    path: /stages/{id}
    controller: App\Controller\ProStageController::stages

ProStageController_parEntreprise:
    path: /entreprises/{id}
    controller: App\Controller\ProStageController::parEntreprise

ProStageController_parFormation:
    path: /formations/{id}
    controller: App\Controller\ProStageController::parFormation

ProStageController_ajouterEntreprise:
    path: /ajouterEntreprise
    controller: App\Controller\ProStageController::ajouterEntreprise

ProStageController_modifierEntreprise:
    path: /entreprises/{id}/modifier
    controller: App\Controller\ProStageController::modifierEntreprise

ProStageController_ajouterStage:
    path: /ajouterStage
    controller: App\Controller\ProStageController::ajouterStage

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

